USE ROLE ROLE_LOADER;
USE WAREHOUSE MODERN_INSURANCE_PLATFORM_WH;

USE DATABASE PRD_MODERN_INSURANCE_PLATFORM;
USE SCHEMA RAW;

TRUNCATE TABLE BUSINESS_EVENTS;
TRUNCATE TABLE CLAIMS;
TRUNCATE TABLE POLICIES;
TRUNCATE TABLE CUSTOMERS;
